# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20171016_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 10, 17, 4, 15, 16, 678434), verbose_name='Опубликована'),
        ),
    ]
