# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 04:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20171017_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 10, 17, 7, 29, 10, 717184), verbose_name='Опубликована'),
        ),
    ]
