# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20171017_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 10, 20, 13, 12, 16, 157696), verbose_name='Опубликована'),
        ),
    ]
